"use client";
import {createContext, useContext, useEffect, useState} from "react";
import {api, clearCsrfToken, resetAuthCsrf} from "@/lib/api";
import type {User} from "@/lib/types";
export type AuthStatus = "loading" | "authenticated" | "anonymous" | "error";
type Ctx={user:User|null;authStatus:AuthStatus;authOpen:boolean;composerOpen:boolean;openAuth:()=>void;openComposer:()=>void;close:()=>void;refresh:()=>Promise<User|null>};
const Context=createContext<Ctx|null>(null); export function useApp(){const v=useContext(Context);if(!v)throw Error("Missing AppProvider");return v}
export function AppProvider({children}:{children:React.ReactNode}){const[user,setUser]=useState<User|null>(null),[authStatus,setAuthStatus]=useState<AuthStatus>("loading"),[authOpen,setAuth]=useState(false),[composerOpen,setComposer]=useState(false);const refresh=async()=>{try{const x=await api<{user:User|null}>("/auth/me/");setUser(x.user);setAuthStatus(x.user?"authenticated":"anonymous");return x.user}catch{setUser(null);setAuthStatus("error");throw new Error("Unable to verify your session. Check the application server and cookie settings.")}};useEffect(()=>{void refresh().catch(()=>undefined)},[]);const close=()=>{setAuth(false);setComposer(false)};return <Context.Provider value={{user,authStatus,authOpen,composerOpen,openAuth:()=>setAuth(true),openComposer:()=>user?setComposer(true):setAuth(true),close,refresh}}>{children}<AuthDialog/><ComposerDialog/></Context.Provider>}
function AuthDialog(){const{authOpen,close,refresh}=useApp();const[mode,setMode]=useState<"login"|"register">("login"),[error,setError]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>setError(""),[mode]);if(!authOpen)return null;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const d=Object.fromEntries(new FormData(e.currentTarget));try{const result=await api<{user:User}>(`/auth/${mode}/`,{method:"POST",body:JSON.stringify(d)});clearCsrfToken();const verified=await refresh();if(!verified||verified.id!==result.user.id)throw new Error("Sign-in succeeded, but the session could not be verified. Check that cookies are enabled and the proxy preserves Set-Cookie headers.");await resetAuthCsrf();close()}catch(x){setError(x instanceof Error?x.message:"Unable to sign in.")}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&close()}><dialog open aria-modal="true" aria-labelledby="auth-title"><button className="dialogClose" onClick={close} disabled={busy} aria-label="Close">×</button><h2 id="auth-title">{mode==="login"?"Welcome back":"Join Insight"}</h2><p>Continue the conversation without losing your place.</p><form onSubmit={submit}>{mode==="register"&&<><label>Display name<input name="display_name" required disabled={busy}/></label><label>Email<input name="email" type="email" required disabled={busy}/></label></>}<label>Username<input name="username" required disabled={busy}/></label><label>Password<input name="password" type="password" minLength={mode==="register"?8:undefined} required disabled={busy}/></label>{mode==="register"&&<small>Password must contain at least 8 characters.</small>}{error&&<p className="formError" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></form><button className="textButton" disabled={busy} onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"I already have an account"}</button></dialog></div>}
function ComposerDialog(){const{composerOpen,close}=useApp();const[body,setBody]=useState(""),[type,setType]=useState("short"),[title,setTitle]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");useEffect(()=>{const v=localStorage.getItem("insight-draft");if(v)setBody(v)},[]);useEffect(()=>{localStorage.setItem("insight-draft",body)},[body]);if(!composerOpen)return null;async function publish(){setBusy(true);setError("");try{await api("/posts/",{method:"POST",body:JSON.stringify({body,title,type})});setBody("");localStorage.removeItem("insight-draft");close();window.dispatchEvent(new Event("insight:feed-refresh"))}catch(x){setError(x instanceof Error?x.message:"Publishing failed.")}finally{setBusy(false)}}return <div className="overlay"><dialog open aria-modal="true"><button className="dialogClose" onClick={close} disabled={busy}>×</button><h2>Create</h2><div className="typeSwitch"><button className={type==="short"?"active":""} onClick={()=>setType("short")}>Post</button><button className={type==="article"?"active":""} onClick={()=>setType("article")}>Article</button></div>{type==="article"&&<input className="titleInput" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Article title"/>}<textarea autoFocus value={body} onChange={e=>setBody(e.target.value)} placeholder="What deserves attention?" rows={8}/>{error&&<p className="formError">{error}</p>}<div className="dialogActions"><span>{body.length}/30,000</span><button className="primary" disabled={busy||!body.trim()} onClick={publish}>{busy?"Publishing…":"Publish"}</button></div></dialog></div>}
