"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {User,Comment} from "@/lib/types";
import {api,validateCommentsResponse} from "@/lib/api";
import {CloseIcon} from "../Icons";
import {CommentComposer} from "./CommentComposer";
import {CommentItem} from "./CommentItem";
import {publishCommentsCount} from "./comments-events";
import styles from "./CommentsSheet.module.css";

export type CommentsTarget={postId:string;postAuthor:User;commentCount:number;focusCommentId?:string|null;opener?:HTMLElement|null};
export function CommentsSheet({target,onClose}:{target:CommentsTarget|null;onClose:()=>void}){const[comments,setComments]=useState<Comment[]>([]),[status,setStatus]=useState<"loading"|"success"|"error">("loading"),[count,setCount]=useState(0),[drag,setDrag]=useState(0),sheet=useRef<HTMLDivElement>(null),close=useRef<HTMLButtonElement>(null),start=useRef({y:0,time:0}),targetRef=useRef(target);targetRef.current=target;
  const dismiss=useCallback(()=>{targetRef.current?.opener?.focus();onClose()},[onClose]);
  const load=useCallback(async()=>{if(!target)return;setStatus("loading");try{const value=validateCommentsResponse(await api<unknown>(`/posts/${target.postId}/comments/`));let results=value.results;if(target.focusCommentId&&!results.some(c=>c.id===target.focusCommentId||c.replies?.some(r=>r.id===target.focusCommentId))){const context=await api<{context:{root:Comment;replies:Comment[]}}>(`/comments/${target.focusCommentId}/context/`);const root={...context.context.root,replies:context.context.replies};results=[root,...results.filter(c=>c.id!==root.id)]}setComments(results);setCount(typeof value.total_count==="number"?value.total_count:target.commentCount);setStatus("success")}catch{setStatus("error")}},[target]);
  useEffect(()=>{if(!target)return;void load();const overflow=document.body.style.overflow;document.body.style.overflow="hidden";close.current?.focus();history.pushState({comments:true},"");const pop=()=>dismiss();addEventListener("popstate",pop);return()=>{document.body.style.overflow=overflow;removeEventListener("popstate",pop)}},[target,load,dismiss]);
  useEffect(()=>{if(status!=="success"||!target?.focusCommentId)return;requestAnimationFrame(()=>{const node=document.getElementById(`comment-${target.focusCommentId}`);node?.scrollIntoView({block:"center"});node?.setAttribute("tabindex","-1");node?.focus({preventScroll:true});node?.classList.add(styles.highlight);setTimeout(()=>node?.classList.remove(styles.highlight),1800)})},[status,target]);
  if(!target)return null;function created(comment:Comment,next:number){setComments(v=>[comment,...v]);setCount(next);publishCommentsCount(target!.postId,next)}function deleted(id:string,next:number){setComments(v=>v.filter(c=>c.id!==id));setCount(next);publishCommentsCount(target!.postId,next)}
  function down(e:React.PointerEvent){start.current={y:e.clientY,time:performance.now()};e.currentTarget.setPointerCapture(e.pointerId)}function move(e:React.PointerEvent){if(!e.currentTarget.hasPointerCapture(e.pointerId))return;setDrag(Math.max(0,e.clientY-start.current.y))}function up(e:React.PointerEvent){const velocity=drag/Math.max(1,performance.now()-start.current.time),threshold=(sheet.current?.offsetHeight||600)*.25;e.currentTarget.releasePointerCapture(e.pointerId);if(drag>threshold||velocity>.7)dismiss();else setDrag(0)}
  return <div className={styles.backdrop} style={{"--drag":`${drag}px`} as React.CSSProperties} onPointerDown={e=>e.target===e.currentTarget&&dismiss()}><div ref={sheet} className={styles.sheet} role="dialog" aria-modal="true" aria-labelledby="comments-title" style={{transform:`translateY(${drag}px)`}} onKeyDown={e=>{if(e.key==="Escape")dismiss();if(e.key==="Tab"){const nodes=sheet.current?.querySelectorAll<HTMLElement>('button,input,textarea,[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header className={styles.header} onPointerDown={down} onPointerMove={move} onPointerUp={up}><span className={styles.handle}/><div><h2 id="comments-title">Replies · {count}</h2><button ref={close} onClick={dismiss} aria-label="Close replies"><CloseIcon/></button></div></header><main className={styles.list}>{status==="loading"?<div role="status" aria-label="Loading replies">{[1,2,3,4].map(x=><div className={styles.skeleton} key={x}><i/><span/><span/><span/></div>)}</div>:status==="error"?<div className="error"><h3>Unable to load replies</h3><p>The server could not complete the request.</p><button className="secondary" onClick={()=>void load()}>Retry</button></div>:comments.length?comments.map(c=><CommentItem key={c.id} initial={c} onDeleted={deleted}/>):<div className="empty"><h3>No replies yet</h3><p>Start the conversation.</p></div>}</main><CommentComposer postId={target.postId} onCreated={created}/></div></div>}
