import {beforeEach, describe, expect, it, vi} from "vitest";

const json = (value: unknown, status = 200) => new Response(status === 204 ? null : JSON.stringify(value), {status, headers: {"Content-Type": "application/json", "X-Request-ID": "request-1"}});

describe("API client", () => {
  beforeEach(() => { vi.resetModules(); vi.unstubAllGlobals(); });
  it("returns successful JSON", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json({ok: true}))); const {api} = await import("../lib/api"); await expect(api("/health/")).resolves.toEqual({ok: true}); });
  it("preserves JSON validation errors", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json({error: {code: "invalid", message: "Check that field"}}, 400))); const {api} = await import("../lib/api"); await expect(api("/bad/")).rejects.toMatchObject({status: 400, code: "invalid", message: "Check that field"}); });
  it.each([["plain text", "text/plain"], ["<html>bad gateway</html>", "text/html"]])("hides invalid server bodies", async (body, type) => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(body, {status: 502, headers: {"Content-Type": type}}))); const {api} = await import("../lib/api"); await expect(api("/bad/")).rejects.toMatchObject({code: "invalid_response", message: "The server returned an invalid response. Please retry."}); });
  it("translates network rejection", async () => { vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new TypeError("Failed to fetch"))); const {api} = await import("../lib/api"); await expect(api("/feed/")).rejects.toMatchObject({code: "network_error", message: "The server could not be reached. Check your connection and retry."}); });
  it("handles an empty 204", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(undefined, 204))); const {api} = await import("../lib/api"); await expect(api("/post/", {method: "GET"})).resolves.toBeUndefined(); });
  it("distinguishes caller cancellation", async () => { vi.stubGlobal("fetch", vi.fn((_url, init: RequestInit) => new Promise((_resolve, reject) => init.signal?.addEventListener("abort", () => reject(new DOMException("Aborted", "AbortError")))))); const {api} = await import("../lib/api"); const controller = new AbortController(), promise = api("/feed/", {signal: controller.signal}); controller.abort(); await expect(promise).rejects.toMatchObject({code: "request_aborted"}); });
  it("shares CSRF bootstrap and clears it after auth", async () => { const fetch = vi.fn().mockImplementation(() => Promise.resolve(json({csrfToken: "one"}))); vi.stubGlobal("fetch", fetch); const {getCsrfToken, resetAuthCsrf} = await import("../lib/api"); await Promise.all([getCsrfToken(), getCsrfToken()]); expect(fetch).toHaveBeenCalledTimes(1); resetAuthCsrf(); await getCsrfToken(); expect(fetch).toHaveBeenCalledTimes(2); });
  it("retries a confirmed CSRF failure exactly once", async () => { const fetch = vi.fn().mockResolvedValueOnce(json({csrfToken: "one"})).mockResolvedValueOnce(json({error: {code: "csrf_failed", message: "expired"}}, 403)).mockResolvedValueOnce(json({csrfToken: "two"})).mockResolvedValueOnce(json({ok: true})); vi.stubGlobal("fetch", fetch); const {api} = await import("../lib/api"); await expect(api("/posts/", {method: "POST", body: "{}"})).resolves.toEqual({ok: true}); expect(fetch).toHaveBeenCalledTimes(4); });
  it("does not retry ordinary permission failures", async () => { const fetch = vi.fn().mockResolvedValueOnce(json({csrfToken: "one"})).mockResolvedValueOnce(json({error: {code: "forbidden", message: "Forbidden"}}, 403)); vi.stubGlobal("fetch", fetch); const {api} = await import("../lib/api"); await expect(api("/posts/", {method: "POST", body: "{}"})).rejects.toMatchObject({code: "forbidden"}); expect(fetch).toHaveBeenCalledTimes(2); });
});
