import {describe,expect,it} from "vitest";import {readFileSync} from "node:fs";import {join} from "node:path";
const root=join(import.meta.dirname,".."),read=(path:string)=>readFileSync(join(root,path),"utf8");
describe("social refinements",()=>{
  it("uses an icon-only accessible comment send action",()=>{const source=read("components/comments/CommentComposer.tsx");expect(source).toContain("<SendIcon/>");expect(source).toContain('aria-label="Post comment"');expect(source).not.toMatch(/>Reply<|Replying…/)});
  it("preserves comment drafts and clears only after success",()=>{const source=read("components/comments/CommentComposer.tsx");expect(source).toContain("localStorage.setItem(key,body)");expect(source.indexOf('setBody("")')).toBeGreaterThan(source.indexOf("await api"))});
  it("uses semantic guest and brand avatars",()=>{const avatar=read("components/Avatar.tsx"),notifications=read("components/notifications/NotificationRow.tsx");expect(avatar).toContain('variant==="brand"?"J":"R"');expect(notifications).toContain('variant="brand"');expect(avatar).not.toContain('fallback="?"')});
  it("opens one global share sheet",()=>{const provider=read("components/AppProvider.tsx"),card=read("components/ContentCard.tsx");expect(provider).toContain("<ShareSheet");expect(card).toContain("openShare(");expect(card).not.toContain("navigator.share")});
  it("provides encoded platform intents and honest Instagram fallback",()=>{const sheet=read("components/sheets/ShareSheet.tsx");expect(sheet).toContain("encodeURIComponent");expect(sheet).toContain("facebook.com/sharer");expect(sheet).toContain("twitter.com/intent/tweet");expect(sheet).toContain("Paste it into Instagram")});
  it("does not count cancelled native shares",()=>{const sheet=read("components/sheets/ShareSheet.tsx"),native=sheet.slice(sheet.indexOf("const native="),sheet.indexOf("const actions="));expect(native.indexOf("await record(channel)")).toBeGreaterThan(native.indexOf("await navigator.share"));expect(native).toContain('error.name==="AbortError"')});
  it("uses canonical notification counts and query navigation",()=>{const page=read("app/notifications/page.tsx");expect(page).toContain("setUnreadCount(value.unread_count)");expect(page).toContain("?comments=1");expect(page).not.toContain("#comment-")});
  it("implements directional swipe locking",()=>{const row=read("components/notifications/NotificationRow.tsx");expect(row).toMatch(/"horizontal"\s*\|\s*"vertical"/);expect(row).toMatch(/Math\.abs\(dx\)\s*>\s*Math\.abs\(dy\)\s*\+\s*5/);expect(read("components/notifications/NotificationRow.module.css")).toMatch(/touch-action:\s*pan-y/)});
  it("shows deletion only when the backend grants it",()=>{const card=read("components/ContentCard.tsx"),menu=read("components/posts/PostActionsMenu.tsx");expect(card).toContain("viewer_state.can_delete");expect(menu).toContain("Delete post?");expect(menu).not.toContain("window.confirm")});
  it("loads target comment context",()=>{const sheet=read("components/comments/CommentsSheet.tsx");expect(sheet).toContain("/context/");expect(sheet).toContain("scrollIntoView");expect(sheet).toContain("focusCommentId")});
});
